LineLength:
  Max: 200

Encoding:
  Enabled: false
Documentation:
  Enabled: false

TrailingBlankLines:
  Enabled: false

EmptyLinesAroundBody:
  Description: "Keeps track of blank lines around expression bodies."
  Enabled: false