development:
  domain_name: halogeno.us
  from_address: no-reply@halogeno.us
  email_domains: [grinnell.edu, alumni.grinnell.edu, gmail.com]

test:
  domain_name: halogeno.us
  from_address: no-reply@halogeno.us
  email_domains: [blop.blop]

production:
  domain_name: grinnellplans.com
  from_address: no-reply@grinnellplans.com
  email_domains: [grinnell.edu, alumni.grinnell.edu]
